/**
 * Fun Facts Generator
 * Manages different categories of interesting facts
 */

class FactsGenerator {
    constructor() {
        this.currentCategory = null;
        this.factContent = document.getElementById('factContent');
        this.generateBtn = document.getElementById('generateBtn');
        this.factBtns = document.querySelectorAll('.fact-btn');
        
        this.facts = {
            nature: [
                "A single tree can produce enough oxygen for two people for an entire year.",
                "Bamboo is the fastest-growing plant in the world and can grow up to 3 feet in 24 hours.",
                "The Amazon rainforest produces about 20% of the world's oxygen.",
                "Redwood trees can live for over 2,000 years and grow to heights of 350+ feet.",
                "A single raindrop can contain up to 1 million bacteria.",
                "The deepest point on Earth is the Mariana Trench at 36,200 feet below sea level.",
                "Lightning strikes the Earth about 8 million times per day.",
                "The largest living organism is a fungus in Oregon that covers 2,385 acres.",
                "Honey never spoils - archaeologists have found 3,000-year-old honey that's still edible.",
                "A single bolt of lightning contains enough energy to power 150 million light bulbs.",
                "The Arctic Ocean is the smallest and shallowest of the world's oceans.",
                "Some trees communicate with each other through underground fungal networks.",
                "The Earth's magnetic field is generated by molten iron in its core.",
                "A single snowflake can contain up to 200 ice crystals.",
                "The largest flower in the world can grow up to 3 feet in diameter.",
                "Ocean waves can travel thousands of miles across open water.",
                "The oldest living tree is over 5,000 years old.",
                "Forests cover about 31% of the world's land area.",
                "The Grand Canyon was formed over millions of years by the Colorado River.",
                "Some plants can survive in temperatures as low as -40°F."
            ],
            history: [
                "The Great Wall of China isn't visible from space with the naked eye, contrary to popular belief.",
                "Napoleon wasn't actually short - he was 5'7\", which was average height for men in his time.",
                "The shortest war in history lasted only 38-45 minutes between Britain and Zanzibar in 1896.",
                "Ancient Romans used to brush their teeth with urine because they believed it whitened them.",
                "The first computer programmer was Ada Lovelace in 1843.",
                "Vikings never actually wore horned helmets - this is a myth from 19th century operas.",
                "The ancient library of Alexandria was never actually burned down in a single event.",
                "Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid.",
                "The word 'salary' comes from the Latin word for salt, as Roman soldiers were paid in salt.",
                "The printing press was invented around 1440, revolutionizing the spread of knowledge.",
                "Ancient Egyptians were the first to use paper made from papyrus reeds.",
                "The Roman Empire lasted for over 1,000 years.",
                "The first successful airplane flight lasted only 12 seconds.",
                "Ancient Greeks invented the concept of democracy around 500 BCE.",
                "The Silk Road connected East and West for over 1,400 years.",
                "The first postal system was established in ancient Persia around 550 BCE.",
                "Medieval castles had spiral staircases that turned clockwise to disadvantage attackers.",
                "The Black Death killed an estimated 75-200 million people in the 14th century.",
                "The first known use of paper money was in China during the Tang Dynasty.",
                "Ancient Mayans invented the concept of zero independently from other civilizations."
            ],
            cats: [
                "Cats sleep 12-16 hours a day, which means they spend 70% of their lives sleeping.",
                "A cat's purr frequencies (20-50 Hz) can help heal bones and reduce pain.",
                "Cats have a third eyelid called a nictitating membrane for extra protection.",
                "A group of cats is called a 'clowder' and a group of kittens is called a 'kindle'.",
                "Cats can rotate their ears 180 degrees and have 32 muscles controlling each ear.",
                "A cat's nose print is unique, like a human's fingerprint.",
                "Cats can make over 100 different vocal sounds, while dogs can only make about 10.",
                "The oldest known pet cat existed 9,500 years ago in Cyprus.",
                "Cats have excellent night vision and can see in light levels six times lower than humans.",
                "A cat's heart beats twice as fast as a human heart, at 110-140 beats per minute.",
                "Cats have scent glands on their faces, paws, and tails for marking territory.",
                "The richest cat in the world inherited $13 million from its owner.",
                "Cats can run up to 30 mph and jump up to 6 times their length.",
                "A cat's whiskers are roughly as wide as their body and help them judge spaces.",
                "Cats have a special reflective layer in their eyes called the tapetum lucidum.",
                "Ancient Egyptians worshipped cats and mummified them when they died.",
                "Cats spend 30-50% of their waking hours grooming themselves.",
                "A cat's brain is 90% similar to a human brain in structure.",
                "Cats can't taste sweetness due to a genetic mutation.",
                "The world's longest cat measured 48.5 inches from nose to tail tip."
            ],
            tech: [
                "The first computer bug was an actual bug - a moth trapped in a Harvard computer in 1947.",
                "More than 4 billion people use the internet, which is over half the world's population.",
                "The first computer weighed over 27 tons and took up an entire room.",
                "Google processes over 8.5 billion searches per day.",
                "The '@' symbol was used in accounting before it became part of email addresses.",
                "The first webcam was created to monitor a coffee pot at Cambridge University.",
                "There are more possible chess games than there are atoms in the observable universe.",
                "The first YouTube video was uploaded on April 23, 2005, and was only 18 seconds long.",
                "WiFi stands for 'Wireless Fidelity' and was invented in 1997.",
                "The average smartphone has more computing power than the computers used for the Apollo 11 moon landing.",
                "The first computer mouse was made of wood in 1964.",
                "Email was invented before the World Wide Web.",
                "The first digital camera weighed 8 pounds and took 23 seconds to take a photo.",
                "There are more than 1.8 billion websites on the internet.",
                "The term 'spam' for unwanted email comes from a Monty Python sketch.",
                "The first programming language was created in 1883 for the Jacquard loom.",
                "Amazon started as an online bookstore in Jeff Bezos' garage.",
                "The first computer virus was created in 1971 and was called 'The Creeper'.",
                "GPS was initially developed for military use and became available to civilians in 1983.",
                "The internet weighs approximately 50 grams due to the electrons that make up the data."
            ]
        };

        this.init();
    }

    init() {
        this.setupEventListeners();
    }

    setupEventListeners() {
        // Category button listeners
        this.factBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                const category = btn.dataset.category;
                this.selectCategory(category);
                this.generateFact(category);
            });
        });

        // Generate new fact button
        this.generateBtn?.addEventListener('click', () => {
            if (this.currentCategory) {
                this.generateFact(this.currentCategory);
            } else {
                this.showRandomFact();
            }
        });

        // Keyboard shortcuts
        document.addEventListener('keydown', (e) => {
            if (e.key === 'f' && (e.ctrlKey || e.metaKey)) {
                e.preventDefault();
                this.showRandomFact();
            }
        });
    }

    selectCategory(category) {
        this.currentCategory = category;
        
        // Update active button
        this.factBtns.forEach(btn => {
            btn.classList.remove('active');
        });
        
        const activeBtn = document.querySelector(`[data-category="${category}"]`);
        if (activeBtn) {
            activeBtn.classList.add('active');
        }

        // Update generate button text
        if (this.generateBtn) {
            this.generateBtn.innerHTML = `
                <i class="fas fa-refresh"></i>
                Generate New ${this.capitalizeFirst(category)} Fact
            `;
        }
    }

    generateFact(category) {
        if (!this.facts[category] || !this.factContent) return;

        const facts = this.facts[category];
        const randomIndex = Math.floor(Math.random() * facts.length);
        const fact = facts[randomIndex];

        // Add loading animation
        this.factContent.style.opacity = '0.5';
        this.generateBtn.disabled = true;

        setTimeout(() => {
            this.displayFact(fact, category);
            this.factContent.style.opacity = '1';
            this.generateBtn.disabled = false;
        }, 300);
    }

    showRandomFact() {
        const categories = Object.keys(this.facts);
        const randomCategory = categories[Math.floor(Math.random() * categories.length)];
        
        this.selectCategory(randomCategory);
        this.generateFact(randomCategory);
    }

    displayFact(fact, category) {
        if (!this.factContent) return;

        const categoryEmojis = {
            nature: '🌲',
            history: '🏛️', 
            cats: '🐱',
            tech: '💻'
        };

        const categoryColors = {
            nature: '#228B22',
            history: '#8B4513',
            cats: '#FF6B6B',
            tech: '#4A90E2'
        };

        this.factContent.innerHTML = `
            <div class="fact-header" style="color: ${categoryColors[category]}; margin-bottom: 1rem;">
                <span style="font-size: 1.5rem; margin-right: 0.5rem;">${categoryEmojis[category]}</span>
                <span style="font-weight: 600; font-size: 1.1rem;">${this.capitalizeFirst(category)} Fact</span>
            </div>
            <p style="font-size: 1.2rem; line-height: 1.7; color: var(--text-secondary);">${fact}</p>
        `;

        // Add animation
        this.factContent.classList.add('fade-in');
        setTimeout(() => {
            this.factContent.classList.remove('fade-in');
        }, 600);
    }

    capitalizeFirst(str) {
        return str.charAt(0).toUpperCase() + str.slice(1);
    }

    // Method to add custom facts (for future expansion)
    addCustomFact(category, fact) {
        if (!this.facts[category]) {
            this.facts[category] = [];
        }
        this.facts[category].push(fact);
    }

    // Method to get statistics about facts
    getFactsStats() {
        const stats = {};
        Object.keys(this.facts).forEach(category => {
            stats[category] = this.facts[category].length;
        });
        return {
            totalCategories: Object.keys(this.facts).length,
            totalFacts: Object.values(this.facts).reduce((acc, facts) => acc + facts.length, 0),
            categoryCounts: stats
        };
    }

    // Method to export facts (for backup/sharing)
    exportFacts() {
        return JSON.stringify(this.facts, null, 2);
    }

    // Method to search facts
    searchFacts(query) {
        const results = {};
        const searchTerm = query.toLowerCase();

        Object.keys(this.facts).forEach(category => {
            const matchingFacts = this.facts[category].filter(fact => 
                fact.toLowerCase().includes(searchTerm)
            );
            if (matchingFacts.length > 0) {
                results[category] = matchingFacts;
            }
        });

        return results;
    }
}

// Initialize Facts Generator when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    window.factsGenerator = new FactsGenerator();
});

// Export for potential module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = FactsGenerator;
}
